package quiz2;


import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class JDialogPayment extends javax.swing.JDialog {

    /**
     * Creates new form JDialogPayment
     */
    private DecimalFormat df = new DecimalFormat("##,##0.00");
    private int totalAmount;
    private static String input = "";
    private JFrameCashier parent;

    public JDialogPayment(JFrameCashier parent, boolean modal, int totaLAmount) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        jTextFieldAmountDue.setText(df.format(totaLAmount));
        setTotalAmount(totaLAmount);
        jTextFieldAmountDue.setEnabled(false);
        jTextFieldChange.setEnabled(false);
        jButtonPayment.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCash = new javax.swing.JTextField();
        jTextFieldAmountDue = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldChange = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jButtonPayment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payment");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Cash:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 111, 30));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Amount Due:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 130, 30));

        jTextFieldCash.setFont(new java.awt.Font("Courier New", 1, 30)); // NOI18N
        jTextFieldCash.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCashKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCashKeyReleased(evt);
            }
        });
        jPanel3.add(jTextFieldCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 182, 30));

        jTextFieldAmountDue.setFont(new java.awt.Font("Courier New", 1, 30)); // NOI18N
        jTextFieldAmountDue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel3.add(jTextFieldAmountDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 182, 30));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Change:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 111, 30));

        jTextFieldChange.setFont(new java.awt.Font("Courier New", 1, 30)); // NOI18N
        jTextFieldChange.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldChangeActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 182, 30));

        jPanel8.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel9.setPreferredSize(new java.awt.Dimension(0, 10));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel9, java.awt.BorderLayout.NORTH);

        jPanel11.setPreferredSize(new java.awt.Dimension(10, 224));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel11, java.awt.BorderLayout.WEST);

        jPanel1.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel12.setPreferredSize(new java.awt.Dimension(569, 60));

        jButtonPayment.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButtonPayment.setMnemonic('P');
        jButtonPayment.setText("Payment");
        jButtonPayment.setFocusable(false);
        jButtonPayment.setPreferredSize(new java.awt.Dimension(610, 50));
        jButtonPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaymentActionPerformed(evt);
            }
        });
        jPanel12.add(jButtonPayment);

        jPanel1.add(jPanel12, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(432, 247));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCashKeyReleased
        int change = 0;
        int cash = 0;

        if (jTextFieldCash.getText().length() < 1) {
            cash = 0;
            jTextFieldChange.setText("0.00");
            return;
        } else {
            cash = Integer.parseInt(jTextFieldCash.getText());
            change = cash - getTotalAmount();
        }
        jTextFieldChange.setText(String.valueOf(df.format(change)));
        if (change >= 0) {
            jButtonPayment.setEnabled(true);
        } else {
            jButtonPayment.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldCashKeyReleased

    private void jTextFieldCashKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCashKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            panelCashier.setPayment(true);
            parent.modifyCash(jTextFieldCash.getText());
            parent.modifyChange(jTextFieldChange.getText());
            this.dispose();
        }
    }//GEN-LAST:event_jTextFieldCashKeyPressed

    private void jButtonPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaymentActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Are you sure to record this as payment?", "Payment confirmation", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
//            panelCashier.setPayment(true);
            int cash = Integer.parseInt(jTextFieldCash.getText());
            int change = cash - getTotalAmount();
            parent.modifyChange(String.valueOf(change));
            parent.modifyCash(String.valueOf(cash));
            parent.processTransaction();
            this.dispose();
            
        } else {
            this.dispose();
        }
        
    }//GEN-LAST:event_jButtonPaymentActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.input = "";
    }//GEN-LAST:event_formWindowClosed

    private void jTextFieldChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldChangeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPayment;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextFieldAmountDue;
    private javax.swing.JTextField jTextFieldCash;
    private javax.swing.JTextField jTextFieldChange;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the totalAmount
     */
    public int getTotalAmount() {
        return totalAmount;
    }

    /**
     * @param totalAmount the totalAmount to set
     */
    public void setTotalAmount(int totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * @return the input
     */
    public static String getInput() {
        return input;
    }

    /**
     * @param aInput the input to set
     */
    public static void setInput(String aInput) {
        input = input + aInput;
    }

    private void inputNumber() {
        int change = 0;
        int cash = 0;

        if (getInput().isEmpty()) {
            cash = 0;
            jTextFieldChange.setText("0.00");
            return;
        } else {
            jTextFieldCash.setText(getInput());
            cash = Integer.parseInt(jTextFieldCash.getText());
            change = cash - getTotalAmount();
            parent.modifyChange(String.valueOf(change));
        }

        jTextFieldChange.setText(String.valueOf(df.format(change)));
        if (change >= 0) {
            jButtonPayment.setEnabled(true);
        } else {
            jButtonPayment.setEnabled(false);
        }
    }

    private void calculate() {
        Double change = 0.0;
        Double cash = 0.0;

        if (jTextFieldCash.getText().length() < 1) {
            cash = 0.0;
            jTextFieldChange.setText("0.00");
            return;
        } else {
            cash = Double.parseDouble(jTextFieldCash.getText());
            change = cash - getTotalAmount();
        }
        jTextFieldChange.setText(String.valueOf(df.format(change)));
        if (change > 0) {
            jButtonPayment.setEnabled(true);
        } else {
            jButtonPayment.setEnabled(false);
        }
    }


}
